### ISSUE TITLE
Not working on Firefox 44+, because it's unsigned.

### ISSUE THREAD

**Issue by ignacy0109** [txgio/orikaisama#2]
Please sign it, supposedly it only takes as long as making an account on mozilla developer page, adding the add-on there and asking the page to sign it (the process is automatic after that).

Additional info:
Firefox 44+doesn't let you install unsigned apps even if you mess around with about:config settings; xpinstall.signatures.required is still there but it changing the boolean doesn't work any more.

**Comment by tomasgodoicd** [comment]
Thanks for the feedback. I'll try to sign it.

**Comment by tomasgodoicd** [comment]
A lot of error checks are ocurring while trying to sign it on mozilla developer, mainly due to binary files. I need to check out how to sign it with these binary files included.

**Comment by tomasgodoicd** [comment]
@ignacy0109 I've managed to sign it. I've updated the file on the releases section. Now it works on Firefox 44+.
